fullnameOverride: oms-db

image:
  name: postgres
  tag: 9.6.10
  pullPolicy: IfNotPresent

ports:
  - containerPort: 5432

service:
  type: ClusterIP
  ports:
    - port: 5432

env:
  POSTGRES_DB: orderdb

volume:
  name: oms-data
  dataInitializerMountPath: /docker-entrypoint-initdb.d
  dataInitializerConfigmap: postgres-data

