replicaCount: 1

image:
  repository: e-com
  tag: latest
  pullPolicy: Never

containerPorts:
  - containerPort: 80

service:
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 80

namespace:
  name: e-com