replicaCount: 1

image:
  repository: e-com
  tag: latest
  pullPolicy: Never

ports:
  - name: http
    containerPort: 80
    protocol: TCP

service:
  type: ClusterIP
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 80

namespace:
  name: e-com