# message queue related and distributed tracing/Zipkin/Slueth needed to collect logs
spring:
  rabbitmq:
    host: localhost
    port: 5672
    virtual-host: /
    username: guest
    password: guest
    publisher-confirms: true

eureka:
  client:
    serviceUrl:
      defaultZone: http://${app.eureka-server}:8761/eureka/
    initialInstanceInfoReplicationIntervalSeconds: 5
    registryFetchIntervalSeconds: 5
  instance:
    leaseRenewalIntervalInSeconds: 5
    leaseExpirationDurationInSeconds: 5

app.eureka-server: localhost

spring.cloud.stream.defaultBinder: rabbit
spring.zipkin.sender.type: rabbit
spring.sleuth.sampler.probability: 1.0

# WARNING: Exposing all management endpoints over http should only be used during development, must be locked down in production!
management.endpoint.health.show-details: "ALWAYS"
management.endpoints.web.exposure.include: "*"


#    TRACE: The lowest level of logging that provides the most detailed information about what is happening in the application.
#    DEBUG: A level higher than TRACE that provides information about application flow and internal state.
#    INFO: A level higher than DEBUG that provides information about what the application is doing and its status.
#    WARN: A level higher than INFO that indicates potentially harmful situations.
#    ERROR: The highest level of logging that indicates errors that may cause the application to malfunction or fail.

logging:
  level:
    #root: ERROR
    root: INFO
    org.springframework.security: DEBUG
    org.springframework.web.server.adapter.HttpWebHandlerAdapter: TRACE
    com.itsthatjun.ecommerce: DEBUG

---

spring.config.activate.on-profile: docker

spring.rabbitmq.host: rabbitmq

app.eureka-server: eureka

eureka:   # TODO: disabled for now
  client:
    enabled: true

---
spring.config.activate.on-profile: kafka

spring.cloud.stream.defaultBinder: kafka
spring.zipkin.sender.type: kafka

spring.cloud.stream.kafka.binder:
  brokers: kafka
  defaultBrokerPort: 9092

management.health.rabbit.enabled: false
spring.kafka.bootstrap-servers: kafka:9092
spring.cloud.stream.kafka.binder.replication-factor: 1
