server:
  port: 8081

spring:
  application:
    name: search
  elasticsearch:
    uris: http://localhost:9200
    connection-timeout: 5s
    socket-timeout: 5s
  data:
    mongodb:
      auto-index-creation: true
      host: localhost
      port: 27017
      username: mongo
      password: password
      database: searchdatabase
      authentication-database: admin
    elasticsearch:
      client:
        reactive: true
      repositories:
        enabled: true

# tells spring mybatis mapper's xml(sql) located
mybatis:
  mapper-locations:
    - classpath:mapper/*.xml
    - classpath:dao/*.xml

logging:
  level:
    org.springframework.data.elasticsearch.client.WIRE: INFO

---

spring.config.activate.on-profile: docker

spring:
  elasticsearch:
    uris: http://elasticsearch:9200
  data:
    mongodb:
      host: search-db