server:
  port: 8081

spring:
  application:
    name: search
  datasource:
    url: jdbc:postgresql://localhost/springecommerece # need to change localhost for docker-compose
    username: postgres
    password: password
    driverClassName: org.postgresql.Driver
    #initialization-mode: always
  data:
    elasticsearch:
      repositories:
        enabled: true
    mongodb:
      auto-index-creation: true
  elasticsearch:
    rest:
      uris: http://localhost:9200

# tells spring mybatis mapper's xml(sql) located
mybatis:
  mapper-locations:
    - classpath:mapper/*.xml
    - classpath:dao/*.xml

spring.data.mongodb:
  host: localhost
  port: 27017
  database: springecommerece-db

app.eureka-server: localhost

eureka:
  client:
    serviceUrl:
      defaultZone: http://${app.eureka-server}:8761/eureka/
    initialInstanceInfoReplicationIntervalSeconds: 5
    registryFetchIntervalSeconds: 5
  instance:
    leaseRenewalIntervalInSeconds: 5
    leaseExpirationDurationInSeconds: 5

---

spring.config.activate.on-profile: docker

spring:
  datasource.url: jdbc:postgresql://postgres/springecommerece
  elasticsearch:
    rest:
      uris: http://elasticsearch:9200
  data:
    mongodb:
      host: mongodb
      port: 27017
      database: springecommerece

spring.data.mongodb.host: mongodb

app:
  eureka-server: eureka