server:
  port: 8080

app:
  CMS-service:
    host: localhost
    port: 8081
  OMS-service:
    host: localhost
    port: 8082
  PMS-service:
    host: localhost
    port: 8083
  SMS-service:
    host: localhost
    port: 8084
  UMS-service:
    host: localhost
    port: 8085

spring:
  datasource:
    url: jdbc:postgresql://localhost/springecommerece
    username: postgres
    password: password
    driverClassName: org.postgresql.Driver
    #initialization-mode: always
  rabbitmq:
    host: localhost
    port: 5672
    virtual-host: /
    username: guest
    password: guest
    publisher-confirms: true

logging:
  level:
    #root: ERROR
    org:
      springframework:
        security: DEBUG
    com:
      itsthatjun:
        ecommerce: DEBUG

---

spring.config.activate.on-profile: docker

spring:
  datasource.url: jdbc:postgresql://postgres/springecommerece
  rabbitmq:
    host: rabbitmq
    port: 5672
    virtual-host: /
    addresses: rabbitmq:5672

app:
  CMS-service:
    host: cms
    port: 8080
  OMS-service:
    host: oms
    port: 8080
  PMS-service:
    host: pms
    port: 8080
  SMS-service:
    host: sms
    port: 8080
  UMS-service:
    host: ums
    port: 8080
