apiVersion: v1
kind: Service
metadata:
  name: logstash
spec:
  selector:
    app: logstash
  ports:
    - protocol: TCP
      port: 4560
      targetPort: 4560
    - protocol: TCP
      port: 4561
      targetPort: 4561
    - protocol: TCP
      port: 4562
      targetPort: 4562
    - protocol: TCP
      port: 4563
      targetPort: 4563
