fullnameOverride: cms-db

image:
  name: postgres
  tag: 16-bullseye
  pullPolicy: IfNotPresent

ports:
  - containerPort: 5432

service:
  type: ClusterIP
  ports:
    - port: 5432

env:
  POSTGRES_DB: contentdb

volume:
  name: cms-data
  dataInitializerMountPath: /docker-entrypoint-initdb.d
  dataInitializerConfigmap: postgres-data

