fullnameOverride: auth-server

image:
  name: auth-server

env:
  SPRING_PROFILES_ACTIVE: "docker"
  SPRING_CONFIG_LOCATION: file:/config-repo/application.yml,file:/config-repo/auth-server.yml
  POSTGRES_USER: postgres
  POSTGRES_PASSWORD: password

service:
  type: ClusterIP

configmap:
  volumeMounts:
    mountPath: /config-repo
