apiVersion: v2
appVersion: "1.0"
description: A Helm chart for
name: dev-env
version: 1.0.0

dependencies:

  - name: common
    version: 1.0.0
    repository: file://../../common

  - name: app
    version: 1.0.0
    repository: file://../../components/app

  - name: cms
    version: 1.0.0
    repository: file://../../components/cms

  - name: cms-db
    version: 1.0.0
    repository: file://../../components/cms-db

  - name: rabbitmq
    version: 1.0.0
    repository: file://../../components/rabbitmq

