ingress:
  name: dev-env
  host: springecom.me
  paths:
    - path: /
      pathType: ImplementationSpecific
      service: app
      port: 80

    - path: /article
      pathType: Prefix
      service: app
      port: 80

    - path: /brand
      pathType: Prefix
      service: app
      port: 80
    - path: /product
      pathType: Prefix
      service: app
      port: 80
    - path: /review
      pathType: Prefix
      service: app
      port: 80

    - path: /cart
      pathType: Prefix
      service: app
      port: 80
    - path: /order
      pathType: Prefix
      service: app
      port: 80
    - path: /return
      pathType: Prefix
      service: app
      port: 80

    - path: /coupon
      pathType: Prefix
      service: app
      port: 80
    - path: /sale
      pathType: Prefix
      service: app
      port: 80

    - path: /user
      pathType: Prefix
      service: app
      port: 80

    - path: /esProduct/search
      pathType: Prefix
      service: search
      port: 8081
    - path: /esProduct/importAll
      pathType: Prefix
      service: search
      port: 8081

    - path: /swagger
      pathType: Prefix
      service: app
      port: 80
    - path: /swagger-ui.html
      pathType: Prefix
      service: app
      port: 80
    - path: /webjars
      pathType: Prefix
      service: app
      port: 80
    - path: /v2/api-docs
      pathType: Prefix
      service: app
      port: 80

    - path: /login
      pathType: Prefix
      service: auth-server
      port: 80

secrets:

  postgres-server-credentials:
    POSTGRES_USER: postgres
    POSTGRES_PASSWORD: password

  rabbitmq-server-credentials:  # not used yet
    RABBITMQ_DEFAULT_USER: guest
    RABBITMQ_DEFAULT_PASS: guest

  mongodb-server-credentials:   # not used yet
    username: username
    password: password

  postgres-credentials:
    SPRING_DATASOURCE_USERNAME: postgres
    SPRING_DATASOURCE_PASSWORD: password

  paypal-credentials:
    PAYPAL_MODE: sandbox
    PAYPAL_CLIENT_ID: YOUR_PAYPAL_ID
    PAYPAL_CLIENT_SECRET: YOUR_PAYPAL_SECRET

  rabbitmq-credentials:
    username: guest
    password: guest

  mongodb-credentials:
    username: username
    password: password

postgres:
  envFromSecretRefs:
    - postgres-server-credentials

cms-db:
  envFromSecretRefs:
    - postgres-server-credentials

pms-db:
  envFromSecretRefs:
    - postgres-server-credentials

oms-db:
  envFromSecretRefs:
    - postgres-server-credentials

sms-db:
  envFromSecretRefs:
    - postgres-server-credentials

ums-db:
  envFromSecretRefs:
    - postgres-server-credentials

auth-db:
  envFromSecretRefs:
    - postgres-server-credentials

app:
  envFromSecretRefs:
    - postgres-credentials
    - rabbitmq-credentials
    - mongodb-credentials

oms:
  envFromSecretRefs:
    - paypal-credentials
    - postgres-credentials
    - rabbitmq-credentials

cms:
  envFromSecretRefs:
    - postgres-credentials
    - rabbitmq-credentials

pms:
  envFromSecretRefs:
    - postgres-credentials
    - rabbitmq-credentials

sms:
  envFromSecretRefs:
    - postgres-credentials
    - rabbitmq-credentials

ums:
  envFromSecretRefs:
    - postgres-credentials
    - rabbitmq-credentials

search:
  envFromSecretRefs:
    - postgres-credentials
    - rabbitmq-credentials

auth-server:
  envFromSecretRefs:
    - postgres-credentials
    - rabbitmq-credentials