secrets:

  postgres-server-credentials:
    POSTGRES_USER: postgres
    POSTGRES_PASSWORD: password

  rabbitmq-server-credentials:  # not used yet
    RABBITMQ_DEFAULT_USER: guest
    RABBITMQ_DEFAULT_PASS: guest

  mongodb-server-credentials:
    username: mongo
    password: password

  postgres-credentials:
    SPRING_DATASOURCE_USERNAME: postgres
    SPRING_DATASOURCE_PASSWORD: password

  usps-credentials:
    USPS_USERID: YOUR_USPS_CREDENTIAL
    USPS_PASSWORD: YOUR_USPS_PASSWORD

  email-credentials:
    MAIL_USERNAME: YOUR_EMAIL_USERNAME
    MAIL_PASSWORD: YOUR_EMAIL_APP_PASSWORD

  paypal-credentials:
    PAYPAL_MODE: sandbox
    PAYPAL_CLIENT_ID: CLIENT_ID
    PAYPAL_CLIENT_SECRET: CLIENT_SECRET

  rabbitmq-credentials:
    username: guest
    password: guest

  mongodb-credentials:
    username: mongo
    password: password


cms-db:
  envFromSecretRefs:
    - postgres-server-credentials

pms-db:
  envFromSecretRefs:
    - postgres-server-credentials

oms-db:
  envFromSecretRefs:
    - postgres-server-credentials

sms-db:
  envFromSecretRefs:
    - postgres-server-credentials

ums-db:
  envFromSecretRefs:
    - postgres-server-credentials

auth-db:
  envFromSecretRefs:
    - postgres-server-credentials

email-db:
  envFromSecretRefs:
    - postgres-server-credentials

mongodb:
  envFromSecretRefs:
    - mongodb-server-credentials

app:
  envFromSecretRefs:
    - postgres-credentials
    - rabbitmq-credentials

oms:
  envFromSecretRefs:
    - paypal-credentials
    - postgres-credentials
    - rabbitmq-credentials
    - usps-credentials

cms:
  envFromSecretRefs:
    - postgres-credentials
    - rabbitmq-credentials

pms:
  envFromSecretRefs:
    - postgres-credentials
    - rabbitmq-credentials

sms:
  envFromSecretRefs:
    - postgres-credentials
    - rabbitmq-credentials

ums:
  envFromSecretRefs:
    - postgres-credentials
    - rabbitmq-credentials

search:
  envFromSecretRefs:
    - postgres-credentials
    - rabbitmq-credentials

auth-server:
  envFromSecretRefs:
    - mongodb-credentials
    - rabbitmq-credentials

notification:
  envFromSecretRefs:
    - postgres-credentials
    - rabbitmq-credentials
    - email-credentials


# Istio Gateway
gateway:
  - name: e-com-gw
    type: ingress
    selector: ingressgateway
    host: springecom.me
    port:
      name: https
      number: 443
      protocol: HTTPS
    tls:
      credentialName: service-certificate
      mode: SIMPLE
    virtualService:
      name: e-com-vs
      http:
        - exact: /
          destination:
            host: app
            port: 80

        - prefix: /article
          destination:
            host: app
            port: 80

        - prefix: /brand
          destination:
            host: app
            port: 80
        - prefix: /product
          destination:
            host: app
            port: 80
        - prefix: /review
          destination:
            host: app
            port: 80

        - prefix: /cart
          destination:
            host: app
            port: 80
        - prefix: /order
          destination:
            host: app
            port: 80
        - prefix: /return
          destination:
            host: app
            port: 80


        - prefix: /coupon
          destination:
            host: app
            port: 80
        - prefix: /sale
          destination:
            host: app
            port: 80

        - prefix: /user
          destination:
            host: app
            port: 80

        - prefix: /esProduct/search
          destination:
            host: search
            port: 8081
        - prefix: /esProduct/importAll
          destination:
            host: search
            port: 8081

        - prefix: /swagger
          destination:
            host: app
            port: 80
#        - prefix: /swagger-ui.html
#          destination:
#            host: app
#            port: 80
        - prefix: /webjars
          destination:
            host: app
            port: 80
        - prefix: /v2/api-docs
          destination:
            host: app
            port: 80

        - prefix: /login
          destination:
            host: auth-server
            port: 80

#  - name: e-com-health-gw
#    type: health
#    selector: ingressgateway
#    host: springecom.me
#    port:
#      name: https
#      number: 443
#      protocol: HTTPS
#    tls:
#      credentialName: e-com-certificate
#      mode: SIMPLE
#    virtualService:
#      name: e-com-health-vs
#      http:
#        - prefix: /health
#          destination:
#            host: app
#            port: 80


# mTLS
peerAuthentication:
  name: default
  namespace: e-com
  mtls:
    mode: STRICT

destinationRules:
  mode: ISTIO_MUTUAL
  rules:
    - name: auth-server
    - name: app
    - name: cms
    - name: pms
    - name: oms
    - name: sms
    - name: ums
    - name: search
    - name: notification


# JWT Authorization Policy