fullnameOverride: rabbitmq

image:
  name: rabbitmq
  tag: 3.8.11-management
  pullPolicy: IfNotPresent

containerPorts:
  - containerPort: 5672
  - containerPort: 15672

service:
  type: LoadBalancer
  ports:
    - name: rabbitmq
      protocol: TCP
      port: 5672
      targetPort: 5672
    - name: rabbitmq-management
      protocol: TCP
      port: 15672
      targetPort: 15672
