fullnameOverride: kibana

image:
  name: kibana
  tag: 7.17.3
  pullPolicy: IfNotPresent

ports:
  - containerPort: 5601

env:
  ELASTICSEARCH_HOSTS: http://elasticsearch:9200

service:
  type: ClusterIP
  ports:
    - name: http
      protocol: TCP
      port: 5601
      targetPort: 5601
