apiVersion: apps/v1
kind: Deployment
metadata:
  name: cms
  namespace: e-com
  labels:
    app: cms
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cms
  template:
    metadata:
      labels:
        app: cms
    spec:
      containers:
        - name: cms
          image: e-com/cms:latest
          imagePullPolicy: Never
          env:
            - name: SPRING_CONFIG_LOCATION
              value: file:/config-repo/application.yml,file:/config-repo/cms.yml
            - name: SPRING_PROFILES_ACTIVE
              value: docker
            - name: POSTGRES_USER
              value: postgres
            - name: POSTGRES_PASSWORD
              value: password
          volumeMounts:
            - name: cms
              mountPath: /config-repo
          ports:
            - containerPort: 80
      volumes:
        - name: cms
          configMap:
            name: cms
