apiVersion: v1
kind: Service
metadata:
  name: cms
  labels:
    app.kubernetes.io/name: cms
spec:
  type: ClusterIP
  selector:
    app: cms
  ports:
    - name: http
      port: 80
      protocol: TCP