fullnameOverride: notification

image:
  name: notification

env:
  SPRING_PROFILES_ACTIVE: "docker"
  SPRING_CONFIG_LOCATION: file:/config-repo/application.yml,file:/config-repo/notification.yml

service:
  type: ClusterIP

livenessProbe_enabled: true

readinessProbe_enabled: true

configmap:
  volumeMounts:
    mountPath: /config-repo
