fullnameOverride: app

image:
  name: app

env:
  SPRING_PROFILES_ACTIVE: "docker"
  SPRING_CONFIG_LOCATION: file:/config-repo/application.yml,file:/config-repo/app.yml

configmap:
  enabled: true
  volumeMounts:
    mountPath: /config-repo
