fullnameOverride: redis

image:
  name: redis
  tag: 7.0.14
  pullPolicy: IfNotPresent

ports:
  - containerPort: 6379

service:
  type: ClusterIP
  ports:
    - name: redis
      protocol: TCP
      port: 6379
      targetPort: 6379