fullnameOverride: elasticsearch

image:
  repository: registry.hub.docker.com/library
  name: elasticsearch
  tag: 7.12.0
  pullPolicy: IfNotPresent

ports:
  - containerPort: 9200
  - containerPort: 9300

service:
  type: ClusterIP
  ports:
    - protocol: TCP
      port: 9200
      targetPort: 9200
      name: one
    - protocol: TCP
      port: 9300
      targetPort: 9300
      name: two
