fullnameOverride: rabbitmq

image:
  repository: registry.hub.docker.com/library
  name: rabbitmq
  tag: 3.8.11-management
  pullPolicy: IfNotPresent

ports:
  - containerPort: 5672
  - containerPort: 15672

service:
  ports:
    - name: tcp-not-secure
      port: 5672
    - name: http-mgm-ui
      port: 15672
