{{- define "common.istio-mTLS" -}}
apiVersion: security.istio.io/v1beta1
kind: PeerAuthentication
metadata:
  name: default
spec:
  mtls:
    mode: {{ .Values.peerAuthentication.mtls.mode }}
---
{{- range $idx, $dr := .Values.destinationRules.rules }}
apiVersion: networking.istio.io/v1beta1
kind: DestinationRule
metadata:
  name: {{ $dr.name }}
spec:
  host: {{ $dr.name }}
{{- if $dr.subsets }}
{{- with $dr.subsets }}
  subsets:
{{ toYaml . | indent 2 }}
{{- end }}
{{- end }}
  trafficPolicy:
    tls:
      mode: {{ $.Values.destinationRules.mode }}
---
{{- end -}}
{{- end -}}
