apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: release-name-dev-env
  labels:
    app.kubernetes.io/name: dev-env
spec:
  rules:
    - http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: app
                port:
                  name: http