fullnameOverride: elasticsearch

image:
  name: elasticsearch
  tag: 7.17.3
  pullPolicy: IfNotPresent

ports:
  - containerPort: 9200
  - containerPort: 9300

env:
  cluster.name: elasticsearch
  discovery.type: single-node
  ES_JAVA_OPTS: -Xms512m -Xmx1024m

service:
  type: ClusterIP
  ports:
    - name: http
      protocol: TCP
      port: 9200
      targetPort: 9200
    - name: transport
      protocol: TCP
      port: 9300
      targetPort: 9300
