apiVersion: apps/v1
kind: Deployment
metadata:
  name: app
  namespace: e-com
  labels:
    app: app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app
  template:
    metadata:
      labels:
        app: app
    spec:
      containers:
        - name: app
          image: e-com/app:latest
          imagePullPolicy: Never
          env:
            - name: SPRING_CONFIG_LOCATION
              value: file:/config-repo/application.yml,file:/config-repo/app.yml
            - name: SPRING_PROFILES_ACTIVE
              value: docker
          volumeMounts:
            - name: app
              mountPath: /config-repo
          ports:
            - containerPort: 80
      volumes:
        - name: app
          configMap:
            name: app
