fullnameOverride: mongodb

image:
  name: mongo
  tag: 5.0.0
  pullPolicy: IfNotPresent

ports:
  - containerPort: 27017

service:
  type: ClusterIP
  ports:
    - port: 27017

env:
  MONGO_INITDB_ROOT_USERNAME:
  MONGO_INITDB_ROOT_PASSWORD:

volume:
  name:

