fullnameOverride: logstash

image:
  name: logstash
  tag: 7.17.3
  pullPolicy: IfNotPresent

ports:
  - containerPort: 5044
  - containerPort: 9600

service:
  type: ClusterIP
  ports:
    - name: beats
      protocol: TCP
      port: 5044
    - name: monitoring
      protocol: TCP
      port: 9600
