fullnameOverride: sms-db

image:
  repository: registry.hub.docker.com/library
  name: postgres
  tag: 9.6.10
  pullPolicy: IfNotPresent

ports:
  containerPort: 5432

service:
  type: ClusterIP
  ports:
    - port: 5432

env:
  POSTGRES_USER: postgres
  POSTGRES_PASSWORD: password
  POSTGRES_DB: salesdb

volume:
  name: sms-data
  dataInitializerMountPath: /docker-entrypoint-initdb.d
  dataInitializerConfigmap: postgres-data

